### ISSUE TITLE
GPA calculator

### ISSUE THREAD

**Issue by MeMeBigProgrammer** [MyMICDS/MyMICDS-v2-Angular#103]
suggested by some of my classmates, it would be a home page module that grabs your classes, displays them in a list that has a dropdown for letter grades, and will display the calculated GPA.

**Comment by MeMeBigProgrammer** [comment]
Some notes for future reviewers:

- The icon for the home page module is not decided yet, and the one chosen as of now is a placeholder
- Should the GPA automatically update with every input, or should it be calculated and revealed only when a button is pressed?
- what should be the default size of the module?

**Comment by MeMeBigProgrammer** [comment]
I decided to have the GPA calculate only after a button is pressed

**Comment by michaelgira23** [comment]
Would it be helpful to calculate the GPA only when the button is pressed, but also give an indication when the inputs are "out of date" with the output? I can imagine someone changing an A to an A- and freaking out when the GPA is the same, or not noticing that it didn't change.

**Comment by MeMeBigProgrammer** [comment]
definitely something to add, I'll keep this issue open for now.
