### ISSUE TITLE
Dropdown icon duplication error

### ISSUE THREAD

**Issue by MeMeBigProgrammer** [MyMICDS/MyMICDS-v2-Angular#118]
![image](https://user-images.githubusercontent.com/28550422/78499090-33c7ba00-7714-11ea-8574-acb20673d7bb.png)

**Comment by nickbclifford** [comment]
The Font Awesome JS library replaces the `<i>` element that Angular is bound to, so it loses the binding and `ngIf` can't remove the element. To fix this, we should replace our current Font Awesome integration with the official [Angular component](https://github.com/FortAwesome/angular-fontawesome).
