### ISSUE TITLE
Optimize CSS

### ISSUE THREAD

**Issue by MeMeBigProgrammer** [MyMICDS/MyMICDS-v2-Angular#132]
this comes from the [web dev test](https://web.dev).

more info [here](https://web.dev/unused-css-rules/).

**Comment by nickbclifford** [comment]
I'd say this could be a part of #129 as well, since getting rid of unnecessary SCSS nesting (which we have pretty much everywhere) would greatly reduce the network overhead for styles.

**Comment by MeMeBigProgrammer** [comment]
Because this is a duplication of an issue, I'll close this one and append the info to #129
