### ISSUE TITLE
Finish Lazy-Loading of Modules

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2-Angular#24]
Lazy-loading components would allow only necessary parts of the application to be initially loaded. This would help with load times. [Read more here.](https://angular-2-training-book.rangle.io/handout/modules/lazy-loading-module.html)

This would require the project to be separated into different ng modules, which is a good thing as it would increase organization.

**Comment by nickbclifford** [comment]
@michaelgira23 The plan is to start on it this weekend.

**Comment by MeMeBigProgrammer** [comment]
As it turns out, angular doesn't support lazy loading of components only modules.

we might have to solve #55 

or use Ivy as described [here](https://medium.com/angular-in-depth/lazy-load-components-in-angular-596357ab05d8)

**Comment by MeMeBigProgrammer** [comment]
Many of the modules have been lazy loaded with the recent PR

**Comment by MeMeBigProgrammer** [comment]
I'm closing this issue as all of the page/feature modules are lazy loaded
