### ISSUE TITLE
Type-ahead for teacher names

### ISSUE THREAD

**Issue by AsianPsychoBoy** [MyMICDS/MyMICDS-v2-Angular#26]
This step in the creation of classes will reduce the variability of teacher names, and therefore makes it much easier to aggregate users under the same class.

**Comment by michaelgira23** [comment]
Going forward, we don't really even utilize teacher names. We're able to group people by class using their portal feed because each class name is unique. We probably don't need to worry about this, and should eventually get rid of teacher input altogether to simplify the interface.
