### ISSUE TITLE
Form validators for the module options

### ISSUE THREAD

**Issue by AsianPsychoBoy** [MyMICDS/MyMICDS-v2-Angular#30]

**Comment by nickbclifford** [comment]
https://angular.io/guide/form-validation

**Comment by AsianPsychoBoy** [comment]
In order to prevent submitting bad content to the server, we need to put form validation for the module options. I suggest that we put angular form validators into each module option of the MyMICDSModule decorator, and then use it on the form inputs of the module options component

**Comment by michaelgira23** [comment]
MyMICDS Module options are auto-generated from [`module-config.ts`](https://github.com/MyMICDS/MyMICDS-v2-Angular/blob/master/src/app/components/modules/module-config.ts) and therefore will not leave any option for bad data. There is an "Enum" type which allows for a selection of specific predefined values.
