### ISSUE TITLE
Get Events Error alert for First-Time Users without Canvas URL entered

### ISSUE THREAD

**Issue by mathcruncher** [MyMICDS/MyMICDS-v2-Angular#45]
I noticed when I hadn't entered my Canvas URL that I kept getting the "Get Canvas Events Error" alert on the Planner. While it could be possible to address this by adding more detail to the alert, this is just a bug that needs to be fixed so that there aren't any alerts for a person who hasn't entered the Canvas URL.

**Comment by michaelgira23** [comment]
I believed this was fixed via #49
