### ISSUE TITLE
Buttons on Planner Overlap Boundary of Sidebar

### ISSUE THREAD

**Issue by mathcruncher** [MyMICDS/MyMICDS-v2-Angular#47]
I noticed the "Create Event" button overlaps with the background when the browser width changes.
![snip](https://user-images.githubusercontent.com/23127867/31976831-4e57534c-b8ff-11e7-9883-d29c04ccb301.PNG)

**Comment by MeMeBigProgrammer** [comment]
Issue was resolved from what i can see,
