### ISSUE TITLE
Fix planner button layout issue on big screens

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2-Angular#51]
On bigger screens, the "Coming Up" button and the "Refresh Portal/Create Event" button group are on the same row. Normally, they are supposed to be on separate lines.

This is what it looks like on big screens:

![Image Example](https://user-images.githubusercontent.com/6778537/32249108-ced3d9cc-be55-11e7-80a5-349fa68ebb14.PNG)

Compared to what it's supposed to look like on smaller screens:

![This is the ideal planner button. You may not like it, but this is its peak performance.](https://user-images.githubusercontent.com/6778537/32259138-6bff7446-be8c-11e7-969c-c5dcc66d4f9e.PNG)

**Comment by nickbclifford** [comment]
Can the "Coming Up" button not be added to the Bootstrap button group or would that be too cramped?

**Comment by michaelgira23** [comment]
At least on smaller screens, yes. I don't know if we'd want to do that anyways because the 'Coming Up' button only appears when looking at a specific day. The button group persists and remains the same no matter what.
