### ISSUE TITLE
Separate components and shiz into different Angular modules

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2-Angular#55]
[This article](https://medium.com/@tomastrajan/6-best-practices-pro-tips-for-angular-cli-better-developer-experience-7b328bc9db81) (courtesy of @nickbclifford) describes good practice for structuring an Angular application. We should eventually migrate to these good practices from the one monolithic Angular module we have right now.

This would also allow us to implement lazy-loading so the client downloads only what they need to view the current page.

**Comment by MeMeBigProgrammer** [comment]
It seems like a cascading number of issues are arising from the fact that we are using one enormous angular module. It's best if we fix this now to allow lazy loading, which in turn will improve performance and flexibility.
