### ISSUE TITLE
Cap Day Progress Percentage at 3:15

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2-Angular#66]
Sometimes, when there's stuff going on after school, the percentage of the day will be inaccurate because the current algorithm determines the last event on the schedule as the end of school. This should be capped at a maximum of 3:15pm, but should be allowed to be the time of the last class if it's earlier than 3:15, implying it's a half day or something.

**Comment by AsianPsychoBoy** [comment]
I think its better to have the option to include afterschool activities in case you actually want them

**Comment by michaelgira23** [comment]
After-school activities would still be on the schedule, but you think people would want them in the day progress percentage?

**Comment by nickbclifford** [comment]
Should we make it a module option?

**Comment by michaelgira23** [comment]
That would be a good idea.
