### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by AsianPsychoBoy** [MyMICDS/MyMICDS-v2-Angular#8]
drag and drop modules for the home page

**Comment by AsianPsychoBoy** [comment]
update: I have worked on creating components, and creating decorators and classes for modules

**Comment by michaelgira23** [comment]
Module configuration interface is pretty much completed in https://github.com/MyMICDS/MyMICDS-v2-Angular/commit/08a1daa5f0723a696f2eed823dba71d10ec09c67. Now, we should be focusing on making the actual modules.

**Comment by nickbclifford** [comment]
IIRC, I added a list of all the modules I thought we should have as a list in `modules.js`.

**Comment by nickbclifford** [comment]
*in the back end

**Comment by michaelgira23** [comment]
Module development progress can also be tracked in the [Modules Project](https://github.com/MyMICDS/MyMICDS-v2/projects/2) in the back-end.

**Comment by AsianPsychoBoy** [comment]
for the sticky note we need to add background colors and italic/bold text

**Comment by michaelgira23** [comment]
The first iteration of the module drag-and-drop configure interface was finalized in https://github.com/MyMICDS/MyMICDS-v2-Angular/pull/28. Any individual modules development should be referenced at https://github.com/MyMICDS/MyMICDS-v2/projects/2 or in their own issue.
