### ISSUE TITLE
Discrepancy between pi-chart clock and listed schedule

### ISSUE THREAD

**Issue by MeMeBigProgrammer** [MyMICDS/MyMICDS-v2-Angular#85]
Screenshots were taken around 2:50 PM

![screenshot 37](https://user-images.githubusercontent.com/28550422/51154018-06090380-1838-11e9-9afb-ac225d5c9f34.png)
![screenshot 36](https://user-images.githubusercontent.com/28550422/51154007-fdb0c880-1837-11e9-8d48-ec12dd04edb0.png)

Unknown whether this is due to Backend or Front end, either way, it shouldn't say School is Over until 3:15

**Comment by MeMeBigProgrammer** [comment]
What's happening here:
1. the mislabelling of breaks, if something else breaks, and the user somehow has a break period at the end of school. This causes the graph to skip the last break period. 
2. Something is causing a discrepancy between the schedule shown and the one being used in the graph
I'm handling the first one now since it is easier and I think I may have found it. This may be a backend or frontend issue.

**Comment by MeMeBigProgrammer** [comment]
The user was an 8th grader who takes some 9th grade classes, and therefore has a schedule that deviates from a normal user

**Comment by MeMeBigProgrammer** [comment]
The Break saying School has ended was a result of the following code:
```if (currBlock.end !== nextBlock.start) {
				breaks.push({
					class: {
						name: 'Break',
						teacher: null,
						type: ClassType.OTHER,
						block: Block.OTHER,
						color: 'rgba(0, 0, 0, 0.4)',
						textDark: false
					},
					start: currBlock.end,
					end: nextBlock.start
				});
			}
		}
``` 
in progress.component.ts

essentially Breaks end time would be set to whatever the next block would be, with a break that went to the end of school, there was no next class, causing it just to be read as a nonexistent thing.

**Comment by MeMeBigProgrammer** [comment]
a possible way for solving this would be adding an extra if statement to see if the current class/block in the iteration is the last class and have the same code except making the end 3:15. If there's no classes after this one, it should end at 3:15 on a normal school day.

**Comment by michaelgira23** [comment]
Good catch. Do you know the cause of there being a break at the end of the day? Shouldn't this user have a class at the end anyways, or is it because of his unique schedule?

**Comment by MeMeBigProgrammer** [comment]
That was due to another error, this is just to make it less broken.

**Comment by MeMeBigProgrammer** [comment]
Since I have not heard about this issue, I'm closing this.
