### ISSUE TITLE
Lunch module is blank

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2-Angular#88]
Ever since migrating to the new school lunch API, the lunch module on the homepage hasn't worked. Interestingly though, the MyMICDS lunch API should be in the exact same format, besides the category labels?

**Comment by MeMeBigProgrammer** [comment]
Clarification: seems to be a layout error which makes the module blank when the height is 1 unit.

**Comment by michaelgira23** [comment]
Yes, Sam is right. This only happens when the height of the lunch module is 1. This probably means that there is too much text and it is probably hiding it all. We should at least display something on height 1.

![Empty lunch module](https://user-images.githubusercontent.com/6778537/63456060-b3b64380-c413-11e9-9dff-85630b0c5ce7.PNG)

**Comment by MeMeBigProgrammer** [comment]
patched
